apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: webapps  
  labels:
    app: frontend
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest  
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: webapps  
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80
  type: LoadBalancer  
